### ISSUE TITLE
Error : cudnn

### ISSUE THREAD

**Issue by egj1692** [egj1692/DeepAA#8]
2023-02-23 14:39:28.004730: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2023-02-23 14:39:32.694974: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library cudnn64_8.dll
2023-02-23 14:39:34.447296: E tensorflow/stream_executor/cuda/cuda_dnn.cc:352] Loaded runtime CuDNN library: 8.0.5 but source was compiled with: 8.1.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
2023-02-23 14:39:34.461107: E tensorflow/stream_executor/cuda/cuda_dnn.cc:352] Loaded runtime CuDNN library: 8.0.5 but source was compiled with: 8.1.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
Traceback (most recent call last):
  File "DeepAA_search.py", line 215, in <module>
    pretrain()
  File "DeepAA_search.py", line 191, in pretrain
    loss, labels_pred = train_step(images, labels, clip_gradient_norm=5.)
  File "C:\Users\RVlab\anaconda3\envs\deepaa1\lib\site-packages\tensorflow\python\eager\def_function.py", line 889, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\RVlab\anaconda3\envs\deepaa1\lib\site-packages\tensorflow\python\eager\def_function.py", line 950, in _call
    return self._stateless_fn(*args, **kwds)
  File "C:\Users\RVlab\anaconda3\envs\deepaa1\lib\site-packages\tensorflow\python\eager\function.py", line 3024, in __call__
    filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
  File "C:\Users\RVlab\anaconda3\envs\deepaa1\lib\site-packages\tensorflow\python\eager\function.py", line 1961, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "C:\Users\RVlab\anaconda3\envs\deepaa1\lib\site-packages\tensorflow\python\eager\function.py", line 596, in call
    ctx=ctx)
  File "C:\Users\RVlab\anaconda3\envs\deepaa1\lib\site-packages\tensorflow\python\eager\execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[node model/conv2d/Conv2D (defined at DeepAA_search.py:172) ]]
         [[Greater/_10]]
  (1) Unknown:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[node model/conv2d/Conv2D (defined at DeepAA_search.py:172) ]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_step_24915]

Errors may have originated from an input operation.
Input Source operations connected to node model/conv2d/Conv2D:
 images_aug (defined at DeepAA_search.py:191)

Input Source operations connected to node model/conv2d/Conv2D:
 images_aug (defined at DeepAA_search.py:191)

Function call stack:
train_step -> train_step

**Comment by egj1692** [comment]
conda install cudnn=8.1 cudatoolkit=11.2 -c conda-forge
